In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import tensorflow as tf, matplotlib.pyplot as plt
import os

from tensorflow.keras import layers

## Data load

In [3]:
# os.chdir('/content/drive/MyDrive/Cephalogram')
# os.chdir('/content/drive/MyDrive/Cephalogram/workspace/feature_test')
# import ceph_config as cf

# our modules
import utils.ceph_config as cf

model_save_path = os.path.join(os.getcwd(), 'output', f'{cf.RESOLUTION_CONFIG}', 'model')
os.makedirs(model_save_path, exist_ok=True)

image_feature = np.load(os.path.join(os.getcwd(), 'output', f'{cf.RESOLUTION_CONFIG}', 'feature', 'feature.npy'))
binary_array = np.load(os.path.join(os.getcwd(), 'output', f'{cf.RESOLUTION_CONFIG}', 'array', 'binary_array.npy'))
int_array = np.load(os.path.join(os.getcwd(), 'output', f'{cf.RESOLUTION_CONFIG}', 'array', 'int_array.npy'))

image_feature_2 = image_feature.astype('float32')
binary_array_2 = binary_array.astype('float32')
int_array_2 = int_array.astype('float32')


print(image_feature_2.shape)
print(binary_array_2.shape)
print(int_array_2.shape)

print(image_feature_2.dtype)
print(binary_array_2.dtype)
print(int_array_2.dtype)

(6928, 96)
(6928, 3)
(6928,)
float32
float32
float32


In [4]:
# from sklearn.model_selection import train_test_split

# x_train_all, x_test, y_train_all, y_test = train_test_split(image_feature_2, int_array_2, test_size=0.2, random_state=7)
# x_train, x_val, y_train, y_val = train_test_split(x_train_all, y_train_all, test_size=0.1, random_state=7)

# x2_train_all, x2_test, y2_train_all, y2_test = train_test_split(image_feature_2, binary_array, test_size=0.2, random_state=7)
# x2_train, x2_val, y2_train, y2_val = train_test_split(x2_train_all, y2_train_all, test_size=0.1, random_state=7)

# print(x_train.shape)
# print(y_train.shape)
# print(x_val.shape)
# print(y_val.shape)
# print(x_test.shape)
# print(y_test.shape)

from sklearn.model_selection import train_test_split

x_test = image_feature_2[4560:5760]
# x_train_all = image_feature_2[0:4560, 5760:]
x_train_all = np.concatenate((image_feature_2[0:4560], image_feature_2[5760:]))

y_test = int_array_2[4560:5760]
y_train_all = np.concatenate((int_array_2[0:4560], int_array_2[5760:]))

y2_test = binary_array[4560:5760]
y2_train_all = np.concatenate((binary_array[0:4560], binary_array[5760:]))

x_train, x_val, y_train, y_val = train_test_split(x_train_all, y_train_all, test_size=0.1, random_state=7)
_, _, y2_train, y2_val = train_test_split(x_train_all, y2_train_all, test_size=0.1, random_state=7)


print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(y_val.shape)
print(x_test.shape)
print(y_test.shape)

(5155, 96)
(5155,)
(573, 96)
(573,)
(1200, 96)
(1200,)


## 각 model load

In [5]:
model_1 = tf.keras.models.load_model(os.path.join(model_save_path, 'int_model.keras'))
model_2 = tf.keras.models.load_model(os.path.join(model_save_path, 'binary_model.keras'))

predict

In [6]:
prediction_1 = model_1.predict(x_test)
prediction_2 = model_2.predict(x_test)

print(prediction_1.shape)
print(prediction_2.shape)

38/38 [==============================] - 1s 2ms/step
(1200, 8)
(1200, 3)


In [7]:
prediction_1[:10]

array([[9.9884158e-01, 1.1564017e-03, 2.7796057e-07, 3.1806111e-10,
        2.5374136e-15, 2.2456787e-12, 1.0186499e-09, 1.7825098e-06],
       [8.6332526e-04, 9.9913532e-01, 5.6522557e-11, 2.7643401e-07,
        8.5906201e-13, 1.2872731e-15, 1.2415254e-06, 1.2427199e-09],
       [2.6778548e-07, 1.6308525e-10, 9.9958521e-01, 4.1076582e-04,
        3.7672656e-09, 3.8351900e-06, 2.6635425e-15, 5.0217747e-12],
       [6.4794697e-10, 3.9446363e-07, 5.6902826e-04, 9.9942708e-01,
        3.5705382e-06, 6.1543783e-09, 9.0879543e-12, 9.8010445e-15],
       [7.6825211e-15, 2.3017217e-12, 4.8490647e-09, 5.4564288e-07,
        9.9482131e-01, 5.1706866e-03, 7.2911021e-06, 1.9742876e-08],
       [9.8503931e-13, 2.9522992e-16, 2.6427149e-06, 6.9575505e-11,
        3.2564378e-04, 9.9966860e-01, 6.6296191e-10, 3.1383165e-06],
       [1.0250972e-08, 5.8384308e-06, 4.8235874e-16, 1.5113808e-13,
        2.3969520e-07, 1.0830731e-09, 9.9748707e-01, 2.5068917e-03],
       [3.2975643e-06, 1.8788244e-09, 6.5

In [8]:
prediction_2[:10]

array([[2.93911532e-17, 5.80822324e-09, 2.50830396e-08],
       [6.78285138e-16, 1.28638318e-08, 1.00000000e+00],
       [4.58895538e-20, 1.00000000e+00, 5.39680656e-09],
       [2.16386465e-16, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 7.90342747e-05, 4.23466963e-06],
       [1.00000000e+00, 1.29064729e-05, 9.99991417e-01],
       [1.00000000e+00, 9.99996185e-01, 1.03228686e-07],
       [1.00000000e+00, 9.99994993e-01, 9.99999166e-01],
       [4.97178846e-21, 1.69048662e-12, 7.81113929e-09],
       [1.35859504e-20, 5.99136409e-12, 1.00000000e+00]], dtype=float32)

---
### Test

In [9]:
from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix, classification_report

1번째 model의 prediction 결과 재정리

In [10]:
len(prediction_1)

1200

In [11]:
np.argmax(prediction_1[0])

0

In [12]:
y_test[:10]

array([0., 1., 2., 3., 4., 5., 6., 7., 0., 1.], dtype=float32)

In [13]:
pred_class_3 = []

for i, item in enumerate(prediction_1):
    pred_class_3.append(np.argmax(item))

pred_class_4 = np.array(pred_class_3).astype('float32')

In [14]:
pred_class_4[:10]

array([0., 1., 2., 3., 4., 5., 6., 7., 0., 1.], dtype=float32)

2번째 model의 prediction 결과 재정리

In [15]:
pred_class_2 = np.where(prediction_2 > 0.5, 1 , 0)

In [16]:
pred_class_2[:10]

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 1]])

In [17]:
for i, item in enumerate(pred_class_2):
    print(item)
    print(type(item[2]))

    if i==10:
        break

[0 0 0]
<class 'numpy.int64'>
[0 0 1]
<class 'numpy.int64'>
[0 1 0]
<class 'numpy.int64'>
[0 1 1]
<class 'numpy.int64'>
[1 0 0]
<class 'numpy.int64'>
[1 0 1]
<class 'numpy.int64'>
[1 1 0]
<class 'numpy.int64'>
[1 1 1]
<class 'numpy.int64'>
[0 0 0]
<class 'numpy.int64'>
[0 0 1]
<class 'numpy.int64'>
[0 1 0]
<class 'numpy.int64'>


In [18]:
pred_class_5 = []

for i, item in enumerate(pred_class_2):
    if item[0]==0 and item[1]==0 and item[2]==0:
        pred_class_5.append(0)

    elif item[0]==0 and item[1]==0 and item[2]==1:
        pred_class_5.append(1)

    elif item[0]==0 and item[1]==1 and item[2]==0:
        pred_class_5.append(2)

    elif item[0]==0 and item[1]==1 and item[2]==1:
        pred_class_5.append(3)

    elif item[0]==1 and item[1]==0 and item[2]==0:
        pred_class_5.append(4)

    elif item[0]==1 and item[1]==0 and item[2]==1:
        pred_class_5.append(5)

    elif item[0]==1 and item[1]==1 and item[2]==0:
        pred_class_5.append(6)

    elif item[0]==1 and item[1]==1 and item[2]==1:
        pred_class_5.append(7)

In [19]:
pred_class_5[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 0, 1]

In [20]:
pred_class_6 = np.array(pred_class_5).astype('float32')

confusion matrix

---
### Validation data predict

In [21]:
prediction_val_1 = model_1.predict(x_val)
prediction_val_2 = model_2.predict(x_val)

18/18 [==============================] - 0s 1ms/step


In [22]:
pred_val_class_3 = []

for i, item in enumerate(prediction_val_1):
    pred_val_class_3.append(np.argmax(item))

pred_val_class_4 = np.array(pred_val_class_3).astype('float32')

In [23]:
pred_val_class_2 = np.where(prediction_val_2 > 0.5, 1 , 0)

In [24]:
pred_val_class_5 = []

for i, item in enumerate(pred_val_class_2):
    if item[0]==0 and item[1]==0 and item[2]==0:
        pred_val_class_5.append(0)

    elif item[0]==0 and item[1]==0 and item[2]==1:
        pred_val_class_5.append(1)

    elif item[0]==0 and item[1]==1 and item[2]==0:
        pred_val_class_5.append(2)

    elif item[0]==0 and item[1]==1 and item[2]==1:
        pred_val_class_5.append(3)

    elif item[0]==1 and item[1]==0 and item[2]==0:
        pred_val_class_5.append(4)

    elif item[0]==1 and item[1]==0 and item[2]==1:
        pred_val_class_5.append(5)

    elif item[0]==1 and item[1]==1 and item[2]==0:
        pred_val_class_5.append(6)

    elif item[0]==1 and item[1]==1 and item[2]==1:
        pred_val_class_5.append(7)

In [25]:
confusion_matrix(y_val, pred_val_class_4)

array([[65,  0,  0,  0,  0,  0,  0,  0],
       [ 1, 67,  0,  1,  0,  0,  0,  0],
       [ 1,  0, 64,  6,  0,  0,  0,  0],
       [ 0,  0,  5, 90,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 75,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 64,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 68,  1],
       [ 0,  0,  0,  0,  0,  0,  1, 64]])

In [26]:
confusion_matrix(y_val, pred_val_class_5)

array([[65,  0,  0,  0,  0,  0,  0,  0],
       [ 1, 67,  0,  1,  0,  0,  0,  0],
       [ 0,  0, 71,  0,  0,  0,  0,  0],
       [ 0,  0,  4, 91,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 74,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 64,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 68,  1],
       [ 0,  0,  0,  0,  0,  0,  0, 65]])

In [27]:
print(classification_report(y_val, pred_val_class_4))

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98        65
         1.0       1.00      0.97      0.99        69
         2.0       0.93      0.90      0.91        71
         3.0       0.93      0.95      0.94        95
         4.0       1.00      1.00      1.00        75
         5.0       1.00      1.00      1.00        64
         6.0       0.99      0.99      0.99        69
         7.0       0.98      0.98      0.98        65

    accuracy                           0.97       573
   macro avg       0.97      0.97      0.97       573
weighted avg       0.97      0.97      0.97       573



In [28]:
print(classification_report(y_val, pred_val_class_5))

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99        65
         1.0       1.00      0.97      0.99        69
         2.0       0.95      1.00      0.97        71
         3.0       0.99      0.96      0.97        95
         4.0       1.00      0.99      0.99        75
         5.0       0.98      1.00      0.99        64
         6.0       1.00      0.99      0.99        69
         7.0       0.98      1.00      0.99        65

    accuracy                           0.99       573
   macro avg       0.99      0.99      0.99       573
weighted avg       0.99      0.99      0.99       573



---
### Test data에 대해 평가

In [29]:
# classification_report(y_test, prediction_1)

In [30]:
pred_class_2 = np.where(prediction_2 > 0.5, 1 , 0)
confusion_matrix_2 = multilabel_confusion_matrix(y2_test, pred_class_2)

print(confusion_matrix_2)
print('\n')

print(classification_report(y2_test, pred_class_2))

[[[600   0]
  [  0 600]]

 [[597   3]
  [  4 596]]

 [[594   6]
  [  5 595]]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00       600
           1       0.99      0.99      0.99       600
           2       0.99      0.99      0.99       600

   micro avg       0.99      0.99      0.99      1800
   macro avg       1.00      0.99      1.00      1800
weighted avg       1.00      0.99      1.00      1800
 samples avg       0.87      0.87      0.87      1800



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


---

In [31]:
confusion_matrix(y_test, pred_class_4)

array([[147,   3,   0,   0,   0,   0,   0,   0],
       [  3, 147,   0,   0,   0,   0,   0,   0],
       [  0,   0, 148,   2,   0,   0,   0,   0],
       [  0,   0,   3, 147,   0,   0,   0,   0],
       [  0,   0,   0,   0, 143,   6,   1,   0],
       [  0,   0,   0,   0,   2, 147,   0,   1],
       [  0,   0,   0,   0,   0,   0, 144,   6],
       [  0,   0,   0,   0,   0,   0,   2, 148]])

In [32]:
confusion_matrix(y_test, pred_class_5)

array([[149,   0,   1,   0,   0,   0,   0,   0],
       [  2, 148,   0,   0,   0,   0,   0,   0],
       [  1,   0, 149,   0,   0,   0,   0,   0],
       [  0,   1,   2, 147,   0,   0,   0,   0],
       [  0,   0,   0,   0, 146,   3,   1,   0],
       [  0,   0,   0,   0,   1, 148,   0,   1],
       [  0,   0,   0,   0,   1,   0, 146,   3],
       [  0,   0,   0,   0,   0,   1,   0, 149]])

In [33]:
print(classification_report(y_test, pred_class_4))

              precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       150
         1.0       0.98      0.98      0.98       150
         2.0       0.98      0.99      0.98       150
         3.0       0.99      0.98      0.98       150
         4.0       0.99      0.95      0.97       150
         5.0       0.96      0.98      0.97       150
         6.0       0.98      0.96      0.97       150
         7.0       0.95      0.99      0.97       150

    accuracy                           0.98      1200
   macro avg       0.98      0.98      0.98      1200
weighted avg       0.98      0.98      0.98      1200



In [35]:
print(classification_report(y_test, pred_class_5))

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99       150
         1.0       0.99      0.99      0.99       150
         2.0       0.98      0.99      0.99       150
         3.0       1.00      0.98      0.99       150
         4.0       0.99      0.97      0.98       150
         5.0       0.97      0.99      0.98       150
         6.0       0.99      0.97      0.98       150
         7.0       0.97      0.99      0.98       150

    accuracy                           0.98      1200
   macro avg       0.99      0.98      0.99      1200
weighted avg       0.99      0.98      0.99      1200

